In [10]:
import numpy as np
import pandas as pd

In [11]:
data = {
    "Age": [25,30,22,28,35,40,29,25,np.nan,32],
    "Salaire": [2000,2500,np.nan,2700,3000,3500,40000,2000,2800,3100],
    "Score": [80,75,60,90,np.nan,85,70,80,95,65],
    "Sexe": ["Homme","Femme","Homme","Femme","Homme","Homme","Femme","Homme","Femme","Homme"],
    "Ville": ["Kinshasa","Lubumbashi","Goma","Kinshasa","Kisangani","Lubumbashi","Goma","Kinshasa","Lubumbashi","Kinshasa"],
    "Departement": ["IT","Finance","RH",np.nan,"IT","Finance","RH","IT","Finance","IT"]
}

In [12]:
data_employee = pd.DataFrame(data)

In [13]:
data_employee

    Age  Salaire  Score   Sexe       Ville Departement
0  25.0   2000.0   80.0  Homme    Kinshasa          IT
1  30.0   2500.0   75.0  Femme  Lubumbashi     Finance
2  22.0      NaN   60.0  Homme        Goma          RH
3  28.0   2700.0   90.0  Femme    Kinshasa         NaN
4  35.0   3000.0    NaN  Homme   Kisangani          IT
5  40.0   3500.0   85.0  Homme  Lubumbashi     Finance
6  29.0  40000.0   70.0  Femme        Goma          RH
7  25.0   2000.0   80.0  Homme    Kinshasa          IT
8   NaN   2800.0   95.0  Femme  Lubumbashi     Finance
9  32.0   3100.0   65.0  Homme    Kinshasa          IT

# Gestion des données manquantes

## 1. Liste des valeurs manquantes par variable

In [14]:
data_employee.isnull().sum()

Age            1
Salaire        1
Score          1
Sexe           0
Ville          0
Departement    1
dtype: int64

## 2. Liste des types des variables

In [16]:
data_quantitatives = data_employee.select_dtypes(include=[np.number]).columns.tolist()
data_qualitatives = data_employee.select_dtypes(exclude=[np.number]).columns.tolist()

In [17]:
data_quantitatives

['Age', 'Salaire', 'Score']

In [18]:
data_qualitatives

['Sexe', 'Ville', 'Departement']

In [19]:
data_employee["Age"].fillna(data_employee["Age"].mean(), inplace = True )

In [20]:
data_employee["Salaire"].fillna(data_employee["Salaire"].mean(), inplace = True )

In [21]:
data_employee["Score"].fillna(data_employee["Score"].mean(), inplace = True )

In [22]:
data_employee["Departement"].fillna(data_employee["Departement"].mode()[0], inplace = True )

In [23]:
data_employee

         Age       Salaire      Score   Sexe       Ville Departement
0  25.000000   2000.000000  80.000000  Homme    Kinshasa          IT
1  30.000000   2500.000000  75.000000  Femme  Lubumbashi     Finance
2  22.000000   6844.444444  60.000000  Homme        Goma          RH
3  28.000000   2700.000000  90.000000  Femme    Kinshasa          IT
4  35.000000   3000.000000  77.777778  Homme   Kisangani          IT
5  40.000000   3500.000000  85.000000  Homme  Lubumbashi     Finance
6  29.000000  40000.000000  70.000000  Femme        Goma          RH
7  25.000000   2000.000000  80.000000  Homme    Kinshasa          IT
8  29.555556   2800.000000  95.000000  Femme  Lubumbashi     Finance
9  32.000000   3100.000000  65.000000  Homme    Kinshasa          IT

## 3. Vérifications

In [24]:
data_employee.isnull().sum()

Age            0
Salaire        0
Score          0
Sexe           0
Ville          0
Departement    0
dtype: int64